name: estate-service

services:
  scraper: 
    build: ./
    restart: always
    env_file:
      - .env
    ports:
      - ${GRPC_PORT}:5321
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      GRPC_IP: 0.0.0.0
      GRPC_PORT: 5321
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017